create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text not null unique,
  avatar_type text not null default 'glow',
  push_token text,
  timezone text not null default 'Asia/Seoul',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.emotion_tags (
  id bigint generated by default as identity primary key,
  name_ko text not null unique,
  group_name text not null,
  priority int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.stars (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  primary_tag_id bigint not null references public.emotion_tags(id),
  content varchar(80),
  time_bucket text not null check (time_bucket in ('새벽', '아침', '낮', '저녁', '밤')),
  emotion_intensity int not null default 3 check (emotion_intensity between 1 and 5),
  visibility_status text not null default 'public' check (visibility_status in ('public', 'limited', 'private')),
  reaction_count int not null default 0,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  expires_at timestamptz
);

create table if not exists public.star_secondary_tags (
  id uuid primary key default gen_random_uuid(),
  star_id uuid not null references public.stars(id) on delete cascade,
  tag_id bigint not null references public.emotion_tags(id),
  unique (star_id, tag_id)
);

create table if not exists public.reaction_types (
  id bigint generated by default as identity primary key,
  code text not null unique,
  label_ko text not null,
  icon text not null,
  is_active boolean not null default true
);

create table if not exists public.reactions (
  id uuid primary key default gen_random_uuid(),
  star_id uuid not null references public.stars(id) on delete cascade,
  sender_user_id uuid not null references auth.users(id) on delete cascade,
  reaction_type_id bigint not null references public.reaction_types(id),
  created_at timestamptz not null default now(),
  unique (star_id, sender_user_id)
);

create table if not exists public.nudges (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null,
  title text not null,
  body text not null,
  delivered_at timestamptz,
  opened_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.daily_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  log_date date not null,
  star_created boolean not null default false,
  reaction_sent boolean not null default false,
  nudge_opened boolean not null default false,
  streak_count int not null default 0,
  unique (user_id, log_date)
);

create table if not exists public.blocks (
  id uuid primary key default gen_random_uuid(),
  blocker_user_id uuid not null references auth.users(id) on delete cascade,
  blocked_user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (blocker_user_id, blocked_user_id),
  check (blocker_user_id <> blocked_user_id)
);

create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  reporter_user_id uuid not null references auth.users(id) on delete cascade,
  target_star_id uuid not null references public.stars(id) on delete cascade,
  reason text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.star_views (
  id uuid primary key default gen_random_uuid(),
  viewer_user_id uuid not null references auth.users(id) on delete cascade,
  star_id uuid not null references public.stars(id) on delete cascade,
  seen_at timestamptz not null default now(),
  unique (viewer_user_id, star_id)
);

create index if not exists stars_user_created_at_idx on public.stars (user_id, created_at desc);
create index if not exists stars_primary_tag_idx on public.stars (primary_tag_id);
create index if not exists reactions_star_idx on public.reactions (star_id, created_at desc);
create index if not exists daily_logs_user_date_idx on public.daily_logs (user_id, log_date desc);

create or replace function public.current_time_bucket(p_ts timestamptz default now())
returns text
language sql
stable
as $$
  select case
    when extract(hour from p_ts at time zone 'Asia/Seoul') between 0 and 5 then '새벽'
    when extract(hour from p_ts at time zone 'Asia/Seoul') between 6 and 10 then '아침'
    when extract(hour from p_ts at time zone 'Asia/Seoul') between 11 and 16 then '낮'
    when extract(hour from p_ts at time zone 'Asia/Seoul') between 17 and 20 then '저녁'
    else '밤'
  end;
$$;

create or replace function public.upsert_daily_log(
  p_user_id uuid,
  p_log_date date,
  p_star_created boolean default false,
  p_reaction_sent boolean default false,
  p_nudge_opened boolean default false
)
returns void
language plpgsql
security definer
as $$
declare
  v_previous_streak int := 0;
begin
  select streak_count
  into v_previous_streak
  from public.daily_logs
  where user_id = p_user_id
    and log_date = p_log_date - 1;

  insert into public.daily_logs (
    user_id,
    log_date,
    star_created,
    reaction_sent,
    nudge_opened,
    streak_count
  )
  values (
    p_user_id,
    p_log_date,
    p_star_created,
    p_reaction_sent,
    p_nudge_opened,
    coalesce(v_previous_streak, 0) + 1
  )
  on conflict (user_id, log_date)
  do update set
    star_created = public.daily_logs.star_created or excluded.star_created,
    reaction_sent = public.daily_logs.reaction_sent or excluded.reaction_sent,
    nudge_opened = public.daily_logs.nudge_opened or excluded.nudge_opened,
    streak_count = greatest(public.daily_logs.streak_count, excluded.streak_count);
end;
$$;

create or replace function public.create_star(
  p_primary_tag_id bigint,
  p_secondary_tag_ids bigint[] default '{}',
  p_content text default null,
  p_visibility_status text default 'public',
  p_emotion_intensity int default 3
)
returns public.stars
language plpgsql
security definer
as $$
declare
  v_today date := (now() at time zone 'Asia/Seoul')::date;
  v_existing uuid;
  v_star public.stars;
  v_tag_id bigint;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  select id
  into v_existing
  from public.stars
  where user_id = auth.uid()
    and is_deleted = false
    and (created_at at time zone 'Asia/Seoul')::date = v_today
  limit 1;

  if v_existing is not null then
    raise exception 'Only one star per day is allowed in MVP';
  end if;

  if p_content is not null and char_length(p_content) > 80 then
    raise exception 'Star content exceeds 80 characters';
  end if;

  insert into public.stars (
    user_id,
    primary_tag_id,
    content,
    time_bucket,
    visibility_status,
    emotion_intensity
  )
  values (
    auth.uid(),
    p_primary_tag_id,
    p_content,
    public.current_time_bucket(now()),
    p_visibility_status,
    p_emotion_intensity
  )
  returning * into v_star;

  foreach v_tag_id in array p_secondary_tag_ids loop
    insert into public.star_secondary_tags (star_id, tag_id)
    values (v_star.id, v_tag_id)
    on conflict (star_id, tag_id) do nothing;
  end loop;

  perform public.upsert_daily_log(auth.uid(), v_today, true, false, false);

  return v_star;
end;
$$;

create or replace function public.get_constellation_feed(
  p_filter_name text default 'all',
  p_page_limit int default 20,
  p_page_offset int default 0
)
returns table (
  star_id uuid,
  content text,
  primary_tag_name text,
  time_bucket text,
  reaction_count int,
  relation_score int,
  created_at timestamptz
)
language sql
security definer
as $$
  with viewer_context as (
    select
      s.primary_tag_id,
      t.group_name,
      s.time_bucket
    from public.stars s
    join public.emotion_tags t on t.id = s.primary_tag_id
    where s.user_id = auth.uid()
      and s.is_deleted = false
    order by s.created_at desc
    limit 1
  )
  select
    s.id as star_id,
    s.content,
    t.name_ko as primary_tag_name,
    s.time_bucket,
    s.reaction_count,
    (
      case when exists (
        select 1
        from viewer_context vc
        where vc.primary_tag_id = s.primary_tag_id
      ) then 40 else 0 end
      +
      case when exists (
        select 1
        from viewer_context vc
        where vc.group_name = t.group_name
      ) then 20 else 0 end
      +
      case when exists (
        select 1
        from viewer_context vc
        where vc.time_bucket = s.time_bucket
      ) then 15 else 0 end
      +
      case when s.created_at >= now() - interval '24 hours' then 10 else 0 end
      +
      case when not exists (
        select 1
        from public.star_views sv
        where sv.viewer_user_id = auth.uid()
          and sv.star_id = s.id
      ) then 15 else 0 end
      +
      case when s.reaction_count >= 5 then -20 else 0 end
      +
      case when s.user_id = auth.uid() then -30 else 0 end
    )::int as relation_score,
    s.created_at
  from public.stars s
  join public.emotion_tags t on t.id = s.primary_tag_id
  where s.is_deleted = false
    and s.visibility_status = 'public'
    and s.user_id <> auth.uid()
    and not exists (
      select 1 from public.blocks b
      where (b.blocker_user_id = auth.uid() and b.blocked_user_id = s.user_id)
         or (b.blocker_user_id = s.user_id and b.blocked_user_id = auth.uid())
    )
    and not exists (
      select 1
      from public.star_views sv
      where sv.viewer_user_id = auth.uid()
        and sv.star_id = s.id
    )
    and (
      p_filter_name = 'all'
      or (p_filter_name = 'similar' and exists (
        select 1
        from viewer_context vc
        where vc.primary_tag_id = s.primary_tag_id or vc.group_name = t.group_name
      ))
      or (p_filter_name = 'night' and s.time_bucket = '밤')
    )
  order by relation_score desc, s.created_at desc
  limit p_page_limit
  offset p_page_offset;
$$;

create or replace function public.send_reaction(
  p_star_id uuid,
  p_reaction_type_id bigint
)
returns public.reactions
language plpgsql
security definer
as $$
declare
  v_today date := (now() at time zone 'Asia/Seoul')::date;
  v_target_star public.stars;
  v_reaction public.reactions;
  v_count int;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  select *
  into v_target_star
  from public.stars
  where id = p_star_id
    and is_deleted = false;

  if not found then
    raise exception 'Star not found';
  end if;

  if v_target_star.user_id = auth.uid() then
    raise exception 'Self reaction is not allowed';
  end if;

  if exists (
    select 1 from public.blocks b
    where (b.blocker_user_id = auth.uid() and b.blocked_user_id = v_target_star.user_id)
       or (b.blocker_user_id = v_target_star.user_id and b.blocked_user_id = auth.uid())
  ) then
    raise exception 'Blocked relationship';
  end if;

  select count(*)
  into v_count
  from public.reactions r
  where r.sender_user_id = auth.uid()
    and (r.created_at at time zone 'Asia/Seoul')::date = v_today;

  if v_count >= 40 then
    raise exception 'Daily reaction cap exceeded';
  end if;

  insert into public.reactions (
    star_id,
    sender_user_id,
    reaction_type_id
  )
  values (
    p_star_id,
    auth.uid(),
    p_reaction_type_id
  )
  returning * into v_reaction;

  update public.stars
  set reaction_count = reaction_count + 1
  where id = p_star_id;

  insert into public.nudges (
    user_id,
    type,
    title,
    body,
    delivered_at
  )
  values (
    v_target_star.user_id,
    'reaction_received',
    '따뜻한 반응이 도착했어요',
    '누군가 당신의 별을 다정하게 바라봤어요.',
    now()
  );

  perform public.upsert_daily_log(auth.uid(), v_today, false, true, false);

  return v_reaction;
end;
$$;

alter table public.emotion_tags enable row level security;
alter table public.star_secondary_tags enable row level security;
alter table public.reaction_types enable row level security;
alter table public.profiles enable row level security;
alter table public.stars enable row level security;
alter table public.reactions enable row level security;
alter table public.nudges enable row level security;
alter table public.daily_logs enable row level security;
alter table public.blocks enable row level security;
alter table public.reports enable row level security;
alter table public.star_views enable row level security;

create policy "emotion tags are visible to authenticated users"
on public.emotion_tags
for select
to authenticated
using (is_active = true);

create policy "reaction types are visible to authenticated users"
on public.reaction_types
for select
to authenticated
using (is_active = true);

create policy "secondary tags follow visible stars"
on public.star_secondary_tags
for select
to authenticated
using (
  exists (
    select 1
    from public.stars s
    where s.id = star_id
      and s.is_deleted = false
      and s.visibility_status = 'public'
  )
);

create policy "profiles are visible to authenticated users"
on public.profiles
for select
to authenticated
using (true);

create policy "users insert own profile"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

create policy "users update own profile"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "public stars are visible"
on public.stars
for select
to authenticated
using (
  not is_deleted
  and visibility_status = 'public'
  and not exists (
    select 1 from public.blocks b
    where (b.blocker_user_id = auth.uid() and b.blocked_user_id = user_id)
       or (b.blocker_user_id = user_id and b.blocked_user_id = auth.uid())
  )
);

create policy "users insert own stars"
on public.stars
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "users update own stars"
on public.stars
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "users can read related reactions"
on public.reactions
for select
to authenticated
using (
  sender_user_id = auth.uid()
  or exists (
    select 1
    from public.stars s
    where s.id = star_id
      and s.user_id = auth.uid()
  )
);

create policy "users insert own reactions"
on public.reactions
for insert
to authenticated
with check (sender_user_id = auth.uid());

create policy "users manage own nudges"
on public.nudges
for select
to authenticated
using (user_id = auth.uid());

create policy "users manage own daily logs"
on public.daily_logs
for select
to authenticated
using (user_id = auth.uid());

create policy "users manage own blocks"
on public.blocks
for select
to authenticated
using (blocker_user_id = auth.uid());

create policy "users insert own blocks"
on public.blocks
for insert
to authenticated
with check (blocker_user_id = auth.uid());

create policy "users delete own blocks"
on public.blocks
for delete
to authenticated
using (blocker_user_id = auth.uid());

create policy "users file own reports"
on public.reports
for insert
to authenticated
with check (reporter_user_id = auth.uid());

create policy "users read own views"
on public.star_views
for select
to authenticated
using (viewer_user_id = auth.uid());

create policy "users insert own views"
on public.star_views
for insert
to authenticated
with check (viewer_user_id = auth.uid());
